---
name: build

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-examples:
    uses: ./.github/workflows/build_examples.yaml

  build-linux:
    uses: ./.github/workflows/build_linux.yaml

  build-macos:
    uses: ./.github/workflows/build_macos.yaml

  build-builder-image:
    uses: ./.github/workflows/build_builder_image.yaml
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name == github.repository)
    secrets: inherit
