---
name: build-macos

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-macos-static:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: install build deps
        run: |
          brew install coreutils

      - name: setup zig/ci bits
        uses: ./.github/actions/setup

      - name: build the static library
        run: |
          make release-macos-static

  build-macos-dynamic:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: install build deps
        run: |
          brew install coreutils pcre2 libssh2

      - name: setup zig/ci bits
        uses: ./.github/actions/setup

      - name: build the dynamic library
        run: |
          make release-macos-dynamic
