---
name: build-examples

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-examples:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: setup zig/ci bits
        uses: ./.github/actions/setup

      - name: build the examples
        run: |
          make build-examples
