---
name: build-linux

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-linux-static:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: setup zig/ci bits
        uses: ./.github/actions/setup

      - name: build static library
        run: |
          make release-linux-static TARGET=x86_64-linux-gnu

  build-linux-dynamic:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcre2-dev libssh2-1-dev

      - name: setup zig/ci bits
        uses: ./.github/actions/setup

      - name: build the dynamic library
        run: |
          make release-linux-dynamic TARGET=x86_64-linux-gnu
