---
name: lint

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "ZIG_VERSION=$ZIG_VERSION" >> "$GITHUB_ENV"
          echo "ZLINT_VERSION=$ZLINT_VERSION" >> "$GITHUB_ENV"

      - name: setup zig
        uses: https://codeberg.org/mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: install zlint
        run: |
          sudo curl -fsSL \
            "https://github.com/DonIsaac/zlint/releases/download/${ZLINT_VERSION}/zlint-linux-x86_64" \
            -o /usr/local/bin/zlint

          sudo chmod +x /usr/local/bin/zlint
          zlint --version

      - name: run the linters
        run: |
          make lint
