---
name: release

on:
  release:
    types:
      - created

jobs:
  release-source:
    uses: ./.github/workflows/release_source.yaml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-macos:
    uses: ./.github/workflows/release_macos.yaml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-linux:
    uses: ./.github/workflows/release_linux.yaml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit

  release-builder-image:
    uses: ./.github/workflows/release_builder_image.yaml
    with:
      release_tag: ${{ github.ref_name }}
    secrets: inherit
