---
name: release-linux

on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true

jobs:
  release-linux-static:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-linux-gnu
          - runner: ubuntu-latest
            target: x86_64-linux-musl
          - runner: ubuntu-24.04-arm
            target: aarch64-linux-musl

    runs-on: ${{ matrix.runner }}

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: release setup
        run: |
          bash ./build/release_setup.sh ${{ inputs.release_tag }}

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: build shared object
        run: |
          make release-linux-static TARGET=${{ matrix.target }}

      - name: publish shared object
        run: |
          bash ./build/release_publish.sh \
            ${{ inputs.release_tag }} \
            zig-out/${{ matrix.target }}/libscrapli.so.${{ env.RELEASE_VERSION }} \
            zig-out/${{ matrix.target }}/libscrapli-${{ matrix.target }}.so.${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux-dynamic:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-linux-gnu

    runs-on: ${{ matrix.runner }}

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcre2-dev libssh2-1-dev

      - name: release setup
        run: |
          bash ./build/release_setup.sh ${{ inputs.release_tag }}

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: build shared object
        run: |
          make release-linux-dynamic TARGET=${{ matrix.target }}

      - name: publish shared object
        run: |
          bash ./build/release_publish.sh \
            ${{ inputs.release_tag }} \
            zig-out/${{ matrix.target }}/libscrapli.so.${{ env.RELEASE_VERSION }} \
            zig-out/${{ matrix.target }}/libscrapli-${{ matrix.target }}-dynamic.so.${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
